### ISSUE TITLE
编译后是生成.so 库吗

### ISSUE THREAD

**Issue by gxut555** [epico/libpinyin#10]
mkdir bulid     cmake..   make. 操作后没见生成库文件？

**Comment by epico** [comment]
在 src 目录下有 libpinyin.so 文件。

**Comment by gxut555** [comment]
多谢回复，，后面找到了。 如果我要生成静态库，我怎么修改呢？  是有词库吗？

**Comment by epico** [comment]
抱歉，我对 CMake 不太熟悉，不太清楚如何修改 CMakeLists.txt .
