### ISSUE TITLE
fcitx5: can't load library because of undefined symbol: _ZTIN5fcitx19InputMethodEngineV3E

### ISSUE THREAD

**Issue by seayuns** [epico/libpinyin#12]
Failed to load library for addon pinyin on /usr/lib/fcitx5/libpinyin.so. Error: /usr/lib/fcitx5/libpinyin.so: undefined symbol: _ZTIN5fcitx19InputMethodEngineV3E

env: 
archlinux fcitx5
asustx 5.15.13-arch1-1 #1 SMP PREEMPT Wed, 05 Jan 2022 16:20:59

**Comment by epico** [comment]
Please report this issue to fcitx5 upstream.
