### ISSUE TITLE
ibus-libpinyin输入法切换bug（长期没有修复）

### ISSUE THREAD

**Issue by djypku** [epico/libpinyin#13]
抱歉，由于ibus-linpinyin没有开issues，就只好来这里写了。
问题是，从俄语、希腊语等非英文布局键盘切换到ibus-libpinyin的时候，中文输入法无法被激活；需要先切换到英文输入法，才能激活中文输入法。gnome版ibus和“正常的”ibus都有这个问题。
去年向ibus反馈过，ibus的[fujiwarat](https://github.com/fujiwarat)告诉我很可能是因为libpinyin没有写键盘布局，tag'写的是default，这样当输入法切换的时候，就无法转换到英文布局来激活ibus-libpinyin。
[https://github.com/ibus/ibus/issues/2378](https://github.com/ibus/ibus/issues/2378)
我现在在silverbule上不能修改/usr/share的内容，回头我可以用虚拟机自己修改试试看。也请你们注意这个bug，尽快找出原因。
谢谢

**Comment by epico** [comment]
可以将问题报告到 https://github.com/libpinyin/ibus-libpinyin/issues .

**Comment by epico** [comment]
为了让输入法支持其他键盘输入拼音，拼音输入法是使用默认键盘布局的。

Takao Fujiwara 建议在 ibus-libpinyin 添加 keymap 配置选项，但是，目前我还没想好如何支持这个 feature...

**Comment by djypku** [comment]
> 为了让输入法支持其他键盘输入拼音，拼音输入法是使用默认键盘布局的。
> 
> Takao Fujiwara 建议在 ibus-libpinyin 添加 keymap 配置选项，但是，目前我还没想好如何支持这个 feature...

我给一个建议吧，把egine的文件位置改到/etc或者$HOME，然后用户可以自行修改使用的布局。
/usr/share下面的东西一般人不敢改的，而且我silverblue基本上就是改不了（我知道有强行修改的办法）。而/etc好像nix和guix用户也不能改？或许还是优先读$HOME/.local下的东西好了

**Comment by epico** [comment]
已收到 ibus-libpinyin upstream 的问题报告，关闭此报告。
