### ISSUE TITLE
Ngram search 相关 API 有使用文档吗？

### ISSUE THREAD

**Issue by faywong** [epico/libpinyin#15]
新手入门，请教下。

以 https://github1s.com/epico/libpinyin/blob/main/tests/storage/test_ngram.cpp 文件为例，其中的 token 是什么含义？
检索是前缀匹配吗？
得到的 freq 是什么单位（-log10 还是什么）？

背景：想在 Rime 输入法里使用 libpinyin 中的 ngram 算法和 ngram db 来提升组整句的体验。

**Comment by epico** [comment]
token 代表一个词语，freq 的单位是词语的频率。

可以参考 `test_pinyin_lookup.cpp`.

**Comment by epico** [comment]
不客气。
