### ISSUE TITLE
compare_indexed_item_with_phrase_string中会出现与NULL比较？

### ISSUE THREAD

**Issue by xuzhen** [epico/libpinyin#4]
用ibus-libpinyin，在输入特定的内容时会导致ibus-engine-libpinyin段错误，然后就稍微调试了一下，发现问题是出在compare_indexed_item_with_phrase_string函数中，candidate_rhs->m_phrase_string或candidate_lhs->m_phrase_string的值可能为0x0，导致strcmp时出错。

ibus版本是ubuntu 13.10中的1.4.2-0ubuntu2，
libpinyin为0.9.93
ibus-libpinyin是1.6.91+git20130424

libpinyin和ibus-libpinyin我用的是ppa编译的：https://launchpad.net/~xuzhen666/+archive/libpinyin

会出问题的组合有点多，比如“zhed”，出问题时，candidate_lhs->m_phrase_string指向“折兑”，candidate_rhs->m_phrase_string为NULL
又比如"zhes"，candidate_lhs->m_phrase_string为NULL，candidate_rhs->m_phrase_string指向“者”

**Comment by epico** [comment]
ibus-libpinyin 1.6.99.20150203 已发布，
请先打开 "将每个输入记录为新的词汇" 选项，
打开之后，输入的新短语即可通过 "导出" 功能导出。

**Comment by xuzhen** [comment]
谢谢！
