### ISSUE TITLE
fcitx-libpinyin需要libpinyin-tools

### ISSUE THREAD

**Issue by 1dot75cm** [epico/libpinyin#5]
fcitx-libpinyin编译需要以下命令：
- /usr/bin/gen_binary_files
- /usr/bin/gen_unigram
- /usr/bin/import_interpolation

libpinyin不再使用这些工具了么？

**Comment by epico** [comment]
之前，fcitx-libpinyin 提供了繁体中文数据。
现在，libzhuyin 和 ibus-libzhuyin 已经发布，请使用 libzhuyin 的繁体中文数据。
为了方便调试 libpinyin，请使用 libpinyin 或 libzhuyin 自带的中文数据，谢谢。

**Comment by 1dot75cm** [comment]
噢，我看看 谢谢指点

**Comment by epico** [comment]
libpinyin 1.1.0 restored the tools.
