### ISSUE TITLE
libpinyin.so failed to load when compiled with kyotocabinet

### ISSUE THREAD

**Issue by felixonmars** [epico/libpinyin#7]
With the latest commit in fcitx-libpinyin, I am getting the following error when trying to switch to libpinyin:

```
(ERROR-12391 /build/fcitx/src/fcitx-4.2.9/src/lib/fcitx/ime.c:303) IM: open /usr/lib/fcitx/fcitx-libpinyin.so fail /usr/lib/libpinyin.so.6: undefined symbol: _ZTIN12kyotocabinet6ThreadE
```

Looks like libpinyin.so didn't link to kyotocabinet, and the symbol failed to load. I have tried to append `-lkyotocabinet` to `LDFLAGS` and this fixes it.

Please look into it, thanks!~

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libpinyin .

**Comment by epico** [comment]
As libpinyin 1.2.0 is released, close issue.

Feel free to comment it, if the problem still exists.
