### ISSUE TITLE
pinyin::PinyinLookup2::train_result2 fails on`m_user_bigram->store(last_token, user)'

### ISSUE THREAD

**Issue by felixonmars** [epico/libpinyin#8]
When selecting any non-default candidate in fcitx-libpinyin, it crashes immediately.

```
fcitx: pinyin_lookup2.cpp:599: bool pinyin::PinyinLookup2::train_result2(ChewingKeyVector, CandidateConstraints, MatchResults): Assertion `m_user_bigram->store(last_token, user)' failed.
```

PS: The build was using Kyotocabinet.

`m_db` has value but it seems the db operation failed. @wengxt points out that the error is the db was not opened.

**Comment by epico** [comment]
Please try to clean user data in ~/.cache/ibus/libpinyin/ .

Every time when libpinyin changes file format or model data, the table.conf will be changed, and user data will be automatically cleaned.

**Comment by felixonmars** [comment]
I have tried to clean the whole folder, but it didn't help if built with Kyotocabinet. Rebuilding with bdb and cleaning the folder again will get it to work.

**Comment by epico** [comment]
Does ibus-libpinyin 1.7.2 work with Kyoto Cabinet?

Sorry, not test much with libpinyin Kyoto Cabinet build...

**Comment by epico** [comment]
Okay, I will try ibus-libpinyin 1.7.2 with Kyoto Cabinet later. :)

**Comment by epico** [comment]
Draft fixes landed on https://github.com/epico/libpinyin .

**Comment by epico** [comment]
As libpinyin 1.2.0 is released, close issue.

Feel free to comment it, if the problem still exists.
